# Generated by Django 3.2.13 on 2022-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
