# Generated by Django 3.2.13 on 2022-05-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='product',
            new_name='doctor',
        ),
    ]
